require './gulp-tasks/cleaners.coffee'
require './gulp-tasks/javascript.coffee'
require './gulp-tasks/stylesheets.coffee'
require './gulp-tasks/layout.coffee'
require './gulp-tasks/build.coffee'
require './gulp-tasks/common.coffee'
