version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node-browsers

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy if tests pass and branch is master
          command: bundle exec cap production deploy